// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlmmxnnbabvfbxlxcgol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsbW14bm5iYWJ2ZmJ4bHhjZ29sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODIyMzUsImV4cCI6MjA2NDM1ODIzNX0.nBIYX5RGEWSwgw1cqPvjQ0JA9quLbNqCWc4bUfRXPdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);